Repository Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamA-be, pull requests merged in 2020-08, with the labels that each got.

#9 Enhancment/prettier and scripts
  .prettierrc.js
  package.json
Labels: bug, documentation, enhancement

#13 Touch up/add edit routes
  api/bridges/bridgeModal.js
  api/bridges/bridgeRouter.js
  config/jsdoc.js
Labels: bug, documentation

#21 created CRUD operations/added middlewares for villages
  api/app.js
  api/villages/villageMiddleware.js
  api/villages/villageModel.js
  api/villages/villageRoutes.js
Labels: enhancement
