Repository Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamA-be, pull requests merged in 2020-09, with the labels that each got.

#24 Feature/inserted into db/mosae anthony
  api/bridges/bridgeModal.js
  api/bridges/bridgeRouter.js
  api/profile/profileRouter.js
  api/villages/villageRoutes.js
  config/jsdoc.js
  data/db-config.js
  data/migrations/20200812094608_create-bridges.js
  data/seeds/002_bridges.js
  dbBuilder/seedBridges.js
  dbBuilder/seedVillages.js
  knexfile.js
  package-lock.json
  package.json
Labels: enhancement

#23 trying to return bridge and village data correctly
  api/bridges/bridgeModal.js
  api/bridges/bridgeRouter.js
  api/profile/profileRouter.js
  api/villages/villageRoutes.js
  config/knexfile.js
  data/db-config.js
  data/migrations/20200812094608_create-bridges.js
  data/seeds/002_bridges.js
  package-lock.json
  package.json
Labels: bug

#28 Updated seed name to match migrations, just so it's all clean
  data/seeds/002_bridges.js
Labels: bug

#29 updated validtaion middleware
  __tests__/routes/bridgeRouter.test.js
  __tests__/routes/index.test.js
  __tests__/routes/villagesRouter.test.js
  api/middleware/authMiddleware.js
  data/migrations/20200820101733_create-village.js
  data/seeds/002_bridges.js
  knexfile.js
  package-lock.json
  package.json
Labels: bug

#39 added pagination to search route
  api/bridges/bridgeRouter.js
Labels: enhancement

#40 cached data 10X faster!
  api/bridges/bridgeModal.js
  api/bridges/bridgeRouter.js
  package-lock.json
  package.json
Labels: enhancement

#41 added route to filter data by name,type etc
  api/bridges/bridgeRouter.js
  api/middleware/authMiddleware.js
Labels: enhancement

#44 Feature/update patch route
  api/bridges/bridgeRouter.js
Labels: enhancement

#43 Added docs for new brige routes
  api/bridges/bridgeRouter.js
Labels: documentation
